// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/562589540/jono-gin/internal/app/system/model"
)

func newDept(db *gorm.DB, opts ...gen.DOOption) dept {
	_dept := dept{}

	_dept.deptDo.UseDB(db, opts...)
	_dept.deptDo.UseModel(&model.Dept{})

	tableName := _dept.deptDo.TableName()
	_dept.ALL = field.NewAsterisk(tableName)
	_dept.ID = field.NewUint(tableName, "id")
	_dept.CreatedAt = field.NewTime(tableName, "created_at")
	_dept.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dept.Name = field.NewString(tableName, "name")
	_dept.Principal = field.NewString(tableName, "principal")
	_dept.Email = field.NewString(tableName, "email")
	_dept.Mobile = field.NewString(tableName, "mobile")
	_dept.ParentID = field.NewUint(tableName, "parent_id")
	_dept.Sort = field.NewInt(tableName, "sort")
	_dept.Status = field.NewBool(tableName, "status")
	_dept.Remark = field.NewString(tableName, "remark")
	_dept.Children = deptHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "model.Dept"),
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Children", "model.Dept"),
		},
		Admins: struct {
			field.RelationField
			Dept struct {
				field.RelationField
			}
			RoleSign struct {
				field.RelationField
				Menus struct {
					field.RelationField
					Children struct {
						field.RelationField
					}
					Roles struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Children.Admins", "model.Admin"),
			Dept: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Children.Admins.Dept", "model.Dept"),
			},
			RoleSign: struct {
				field.RelationField
				Menus struct {
					field.RelationField
					Children struct {
						field.RelationField
					}
					Roles struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Children.Admins.RoleSign", "model.Roles"),
				Menus: struct {
					field.RelationField
					Children struct {
						field.RelationField
					}
					Roles struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Children.Admins.RoleSign.Menus", "model.Menu"),
					Children: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Children.Admins.RoleSign.Menus.Children", "model.Menu"),
					},
					Roles: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Children.Admins.RoleSign.Menus.Roles", "model.Roles"),
					},
				},
			},
		},
	}

	_dept.Admins = deptHasManyAdmins{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Admins", "model.Admin"),
	}

	_dept.fillFieldMap()

	return _dept
}

type dept struct {
	deptDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	Name      field.String
	Principal field.String
	Email     field.String
	Mobile    field.String
	ParentID  field.Uint
	Sort      field.Int
	Status    field.Bool
	Remark    field.String
	Children  deptHasManyChildren

	Admins deptHasManyAdmins

	fieldMap map[string]field.Expr
}

func (d dept) Table(newTableName string) *dept {
	d.deptDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dept) As(alias string) *dept {
	d.deptDo.DO = *(d.deptDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dept) updateTableName(table string) *dept {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint(table, "id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.Name = field.NewString(table, "name")
	d.Principal = field.NewString(table, "principal")
	d.Email = field.NewString(table, "email")
	d.Mobile = field.NewString(table, "mobile")
	d.ParentID = field.NewUint(table, "parent_id")
	d.Sort = field.NewInt(table, "sort")
	d.Status = field.NewBool(table, "status")
	d.Remark = field.NewString(table, "remark")

	d.fillFieldMap()

	return d
}

func (d *dept) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dept) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 13)
	d.fieldMap["id"] = d.ID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["name"] = d.Name
	d.fieldMap["principal"] = d.Principal
	d.fieldMap["email"] = d.Email
	d.fieldMap["mobile"] = d.Mobile
	d.fieldMap["parent_id"] = d.ParentID
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["status"] = d.Status
	d.fieldMap["remark"] = d.Remark

}

func (d dept) clone(db *gorm.DB) dept {
	d.deptDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dept) replaceDB(db *gorm.DB) dept {
	d.deptDo.ReplaceDB(db)
	return d
}

type deptHasManyChildren struct {
	db *gorm.DB

	field.RelationField

	Children struct {
		field.RelationField
	}
	Admins struct {
		field.RelationField
		Dept struct {
			field.RelationField
		}
		RoleSign struct {
			field.RelationField
			Menus struct {
				field.RelationField
				Children struct {
					field.RelationField
				}
				Roles struct {
					field.RelationField
				}
			}
		}
	}
}

func (a deptHasManyChildren) Where(conds ...field.Expr) *deptHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deptHasManyChildren) WithContext(ctx context.Context) *deptHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deptHasManyChildren) Session(session *gorm.Session) *deptHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a deptHasManyChildren) Model(m *model.Dept) *deptHasManyChildrenTx {
	return &deptHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

type deptHasManyChildrenTx struct{ tx *gorm.Association }

func (a deptHasManyChildrenTx) Find() (result []*model.Dept, err error) {
	return result, a.tx.Find(&result)
}

func (a deptHasManyChildrenTx) Append(values ...*model.Dept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deptHasManyChildrenTx) Replace(values ...*model.Dept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deptHasManyChildrenTx) Delete(values ...*model.Dept) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deptHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a deptHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

type deptHasManyAdmins struct {
	db *gorm.DB

	field.RelationField
}

func (a deptHasManyAdmins) Where(conds ...field.Expr) *deptHasManyAdmins {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deptHasManyAdmins) WithContext(ctx context.Context) *deptHasManyAdmins {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deptHasManyAdmins) Session(session *gorm.Session) *deptHasManyAdmins {
	a.db = a.db.Session(session)
	return &a
}

func (a deptHasManyAdmins) Model(m *model.Dept) *deptHasManyAdminsTx {
	return &deptHasManyAdminsTx{a.db.Model(m).Association(a.Name())}
}

type deptHasManyAdminsTx struct{ tx *gorm.Association }

func (a deptHasManyAdminsTx) Find() (result []*model.Admin, err error) {
	return result, a.tx.Find(&result)
}

func (a deptHasManyAdminsTx) Append(values ...*model.Admin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deptHasManyAdminsTx) Replace(values ...*model.Admin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deptHasManyAdminsTx) Delete(values ...*model.Admin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deptHasManyAdminsTx) Clear() error {
	return a.tx.Clear()
}

func (a deptHasManyAdminsTx) Count() int64 {
	return a.tx.Count()
}

type deptDo struct{ gen.DO }

type IDeptDo interface {
	gen.SubQuery
	Debug() IDeptDo
	WithContext(ctx context.Context) IDeptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeptDo
	WriteDB() IDeptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeptDo
	Not(conds ...gen.Condition) IDeptDo
	Or(conds ...gen.Condition) IDeptDo
	Select(conds ...field.Expr) IDeptDo
	Where(conds ...gen.Condition) IDeptDo
	Order(conds ...field.Expr) IDeptDo
	Distinct(cols ...field.Expr) IDeptDo
	Omit(cols ...field.Expr) IDeptDo
	Join(table schema.Tabler, on ...field.Expr) IDeptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeptDo
	Group(cols ...field.Expr) IDeptDo
	Having(conds ...gen.Condition) IDeptDo
	Limit(limit int) IDeptDo
	Offset(offset int) IDeptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeptDo
	Unscoped() IDeptDo
	Create(values ...*model.Dept) error
	CreateInBatches(values []*model.Dept, batchSize int) error
	Save(values ...*model.Dept) error
	First() (*model.Dept, error)
	Take() (*model.Dept, error)
	Last() (*model.Dept, error)
	Find() ([]*model.Dept, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dept, err error)
	FindInBatches(result *[]*model.Dept, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Dept) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeptDo
	Assign(attrs ...field.AssignExpr) IDeptDo
	Joins(fields ...field.RelationField) IDeptDo
	Preload(fields ...field.RelationField) IDeptDo
	FirstOrInit() (*model.Dept, error)
	FirstOrCreate() (*model.Dept, error)
	FindByPage(offset int, limit int) (result []*model.Dept, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id uint) (result model.Dept, err error)
	DeleteByID(id uint) (rowsAffected int64, err error)
	DeleteByIDs(ids []uint) (rowsAffected int64, err error)
}

// SELECT * FROM @@table WHERE id=@id
func (d deptDo) GetByID(id uint) (result model.Dept, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM sys_dept WHERE id=? ")

	var executeSQL *gorm.DB
	executeSQL = d.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE id=@id
func (d deptDo) DeleteByID(id uint) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("DELETE FROM sys_dept WHERE id=? ")

	var executeSQL *gorm.DB
	executeSQL = d.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE id IN (@ids)
func (d deptDo) DeleteByIDs(ids []uint) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, ids)
	generateSQL.WriteString("DELETE FROM sys_dept WHERE id IN (?) ")

	var executeSQL *gorm.DB
	executeSQL = d.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

func (d deptDo) Debug() IDeptDo {
	return d.withDO(d.DO.Debug())
}

func (d deptDo) WithContext(ctx context.Context) IDeptDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deptDo) ReadDB() IDeptDo {
	return d.Clauses(dbresolver.Read)
}

func (d deptDo) WriteDB() IDeptDo {
	return d.Clauses(dbresolver.Write)
}

func (d deptDo) Session(config *gorm.Session) IDeptDo {
	return d.withDO(d.DO.Session(config))
}

func (d deptDo) Clauses(conds ...clause.Expression) IDeptDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deptDo) Returning(value interface{}, columns ...string) IDeptDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deptDo) Not(conds ...gen.Condition) IDeptDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deptDo) Or(conds ...gen.Condition) IDeptDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deptDo) Select(conds ...field.Expr) IDeptDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deptDo) Where(conds ...gen.Condition) IDeptDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deptDo) Order(conds ...field.Expr) IDeptDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deptDo) Distinct(cols ...field.Expr) IDeptDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deptDo) Omit(cols ...field.Expr) IDeptDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deptDo) Join(table schema.Tabler, on ...field.Expr) IDeptDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeptDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deptDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeptDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deptDo) Group(cols ...field.Expr) IDeptDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deptDo) Having(conds ...gen.Condition) IDeptDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deptDo) Limit(limit int) IDeptDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deptDo) Offset(offset int) IDeptDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeptDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deptDo) Unscoped() IDeptDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deptDo) Create(values ...*model.Dept) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deptDo) CreateInBatches(values []*model.Dept, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deptDo) Save(values ...*model.Dept) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deptDo) First() (*model.Dept, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dept), nil
	}
}

func (d deptDo) Take() (*model.Dept, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dept), nil
	}
}

func (d deptDo) Last() (*model.Dept, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dept), nil
	}
}

func (d deptDo) Find() ([]*model.Dept, error) {
	result, err := d.DO.Find()
	return result.([]*model.Dept), err
}

func (d deptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dept, err error) {
	buf := make([]*model.Dept, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deptDo) FindInBatches(result *[]*model.Dept, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deptDo) Attrs(attrs ...field.AssignExpr) IDeptDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deptDo) Assign(attrs ...field.AssignExpr) IDeptDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deptDo) Joins(fields ...field.RelationField) IDeptDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deptDo) Preload(fields ...field.RelationField) IDeptDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deptDo) FirstOrInit() (*model.Dept, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dept), nil
	}
}

func (d deptDo) FirstOrCreate() (*model.Dept, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dept), nil
	}
}

func (d deptDo) FindByPage(offset int, limit int) (result []*model.Dept, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deptDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deptDo) Delete(models ...*model.Dept) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deptDo) withDO(do gen.Dao) *deptDo {
	d.DO = *do.(*gen.DO)
	return d
}
